### ISSUE TITLE
Apply freq limits to mp3 track too

### ISSUE THREAD

**Issue by doomsower** [doomsower/melody#1]

**Comment by doomsower** [comment]
Так, похоже эти фильтры работают как-то не так

**Comment by doomsower** [comment]
@artyompal зацени, я поправил band-pass фильтр: f59e11ec0fc064b189484bc834094e13e1c990b1
И вот я еще что подумал: я вот ориентировался на ноты из JSON, кода ставил фильтр и слушал что проигрывается. Т.е. я смотрю, что все ноты серые на графике, но звук при проигрывании мп3 идет. И тут я подумал - это же может быть звук от тех нот, которые есть в мп3 и проходят через фильтр, но их твоя прога в JSON не запихала. Может такое быть?

**Comment by artyompal** [comment]
Прога, конечно же, может выкинуть часть нот. Она пытается фильтровать шум.

**Comment by artyompal** [comment]
Похоже, что работает. Правда, она не полностью заглушает, но уже похоже на правду.
