### ISSUE TITLE
Change frequency bar labels

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#11]
Labels should be decimal multiplies in Herz, like:
* 100, 200, 300, ..., or
* 10, 20, 30, ..., or
* 1, 2, 3, ..., or
* 0.1, 0.2, 0.3,
* etc

(depending on the zoom level)

**Comment by doomsower** [comment]
С этим моментом не очень понятно. Сейчас ось Y - линейная, единица измерения - питч. Т.е. высота одного прямоугольника на графике - 1 питч. Отметки на оси - через одинаковые интервалы в питчах, только подписаны в герцах. Поэтому в герцах значеия не округлены. Дальше по-моему возможны два варианта:
1. Ось Y остается в питчах, но горизонтальные линии ставим на ровных значениях в герцах. Во-первых тогда линии начнут пересекать прямоугольники в произвольных местах. Во-вторых, т.к. шкала экспоненциальная, то при выборе одного шага (например, 100Hz) линии будут размещены неравномерно. Не знаю, насколько хорошо это будет смотреться и насколько это удобно.
2. Ось Y переводим в герцы, тогда прямоугольники будут иметь различную высоту, т.к. разница между,например, 40-41 и 70-71 питчами в герцах сильно различается. Это по-моему будет выглядеть совсем по-уродски.

**Comment by artyompal** [comment]
Решили пока ничего не менять.
