### ISSUE TITLE
Create a mechanism to edit selected notes

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#13]
User needs to move them and change their length, as well as delete them by clicking on tabulature (not melody pane).

**Comment by artyompal** [comment]
Also they might need to split a note into two pieces. Maybe add a context menu with those actions?

**Comment by doomsower** [comment]
@artyompal тут короче интересный вопрос всплыл. Сейчас я добавил возможность растягивать ноты, но оно и раньше была на длинных нотах. Сейчас же проигрывание нот идет через сэмплер, которые играет короткие треки пререндеренных нот. Если нота длиннее этого трека, то звук прерывается раньше того момента, когда курсор доходит до конца прямоугольника ноты. Т.е. тупол ноты звучат не сколько сказано, а сколько длина сэмпла.
Так вот, как надо поступать в таком случае? Точно можно зациклить, наверное можно растянуть попробовать. Ну и я не очень представляю как это на реальном инструменте выглядит. Т.е. ты дергаешь струну на гитаре или жмешь на кнопку пианино, но звук который ты извлекаешь, он как раз имеет кончную длину, как сэмпл.

**Comment by artyompal** [comment]
Зациклить. Ноты бывают длинные. Можно дернуть струну и она будет 10 или
даже 20 сек звучать. Короткие надо прерывать.

**Comment by doomsower** [comment]
Зацикленная нота на гитаре будет звучать как дерганье одной струны. Типы дрынь-дрынь-дрынь. Attack-decay-sustain-release вот это все. Так и должно быть?

**Comment by artyompal** [comment]
Мм нет. Надо decay продлить. Но если просто растянуть, частота же
изменится!

**Comment by doomsower** [comment]
Я не знаю пока как это работает, все эти ADSR конверты выглядят очень мутными для меня

**Comment by doomsower** [comment]
Так, я немного поразбирался че к чему. Судя по доступному API, если у нас есть mp3-звук (миди-нота), то единственный способ сделать его длиннее или короче - это вот этот самый playbackRate, который я применил к мп3-треку [тут](https://github.com/doomsower/melody/issues/25#issuecomment-213017373). Соответственно, это относится и к сэмплам, миди-нотам. Сейчас ноты, которые короче сэмпла, резко обрываются, и это заметно. Их обрывание, наверное, можно сделать более плавным, применив к ним ADSR-envelope по амплитуде. Но это не очень корректно, т.к. сэмпл имеет свою ADSR кривую, и , например, может получиться, что для короткой ноты мы применяем свой ADSR-envelope чисто к фазе attack оригинального сэмпла. Так что хз что с этим делать.
Ну и тем временем, можно посмотреть удаление и изменение продолжительности.

**Comment by artyompal** [comment]
Я придумал, как растягивать ноты. Я так понимаю, что playbackRate изменяет питч: например, если он растягивает ноту в 2 раза, то частота становится в 2 раза ниже (т.е. на октаву ниже или питч на 12 единиц). Тогда чтобы это скомпенсировать, надо просто взять ноту на октаву выше. Хотя может звучать чуть странно, потому что это будет нота на другой струне...

**Comment by doomsower** [comment]
Ну если так поступать, то легко можно выйти за рамки доступных питчей. Ну и это никак не решает проблему нот длинной в 10-20 секунд. Похоже что тут могут помочь только 100% синтезированные звуки.
Кстати подобным образом, только в обратную сторону, реализован эффект pitchShift в tone - они чтобы сделать сдвиг по питчу меняют playbackRate.

**Comment by artyompal** [comment]
Тут ещё нужно, чтобы можно было питч поменять. Прога не всегда идеально угадывает питч. Могут быть шумы и т.д.
