### ISSUE TITLE
Fix note adding behaviour

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#14]
When user adds a note, all previous notes on the same string must be cut at its beginning.

**Comment by artyompal** [comment]
There should be no overlaps with another notes, never. After editing next note might need to be adjusted or deleted.

**Comment by doomsower** [comment]
Update. Тогда получается умный алгоритм должен выглядеть так: попробовать добавить на все струны, если не получается, выдать сообщение об ошибке

**Comment by doomsower** [comment]
Это вроде уже давно сделано.
