### ISSUE TITLE
Optimize performance

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#17]
With the new version of sound2notes, performance deteriorates. Some profiling is required.

**Comment by doomsower** [comment]
Commits f91f3dcee7cf5686d044d718f49a1006d6df5b67, 0c72e7d844c658cd6eb69d4ba6d09587b9531634, 9944433ec1dbf76ae0cd2286b2a8e2a391110ef5, 1c0cbe2410451233df2d8475bec574154c3e663c should improve performance. Closing for now.
