### ISSUE TITLE
Добавить окно Advanced settings при открытии файла

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#23]
Предлагается добавить кнопочку "Advanced..." в диалог открытия файла. По ней должен открываться диалог, в котором можно установить различные параметры проги sound2notes.

Будучи запущенной без параметров, sound2notes выдаёт все возможные параметры. На сегодня, их 9 штук (кроме первого, который обозначает режим работы; нас он не интересует). Для всех этих параметров надо создать контролы для редактирования. Там бывают флоаты, инты и bool (отображать лист-бокс со строками Enable/Disable). Для window-size отображать лист-бокс с вариантами: все степени двойки от 256 до 65536. Для window-function отображать лист-бокс со всеми возможными значениями.

Дефолтные значения всех этих параметров должны быть в конфиге. Для window-function в конфиге хранить не строку, а номер в списке, дефолтное значение установить 3. 

Когда это будет сделано, я установлю в конфиге правильные значения всех параметров; либо же спроси меня, какими они должны быть.

**Comment by doomsower** [comment]
Несколько вопросов.

1. Правильно ли я понимаю, что UI выглядит следующим образом: рядом с кнопкой "открыть" я добавляю, скажем, иконку-шестеренку, которая будет открывать диалог с настройками. Эти настройки будут распространяться на все открываемые файлы. А кнопка открыть по-прежнему открывает стандартный платформенный диалог открытия файла.
2. Я правильно понимаю, что параметр window-size должен также использоваться в клиенте?(сейчас используются `"windowSize": 4096, "samplingFrequency": 44100` из конфиг-файла). Еще какие-то параметры нужны клиенту?
3. Я смотрю, что в консольно выводе sound2notes с --window-size=4096 он пишет что-то про windows per second = 10.77. Т.е. деление идет с округлением. У меня же используется 44100/4096. Это значение используется для пересчета нот в JSON в секунды. Это у тебя чисто в консоле округление или расчет тоже с таким значением идет? Мне наверное надо тогда точно такое же значение юзать.

**Comment by artyompal** [comment]
1. Да. Ну я представлял себе кнопку вроде "Advanced settings>>"
2. Да, размер окна должен использоваться в клиенте. Есть ещё один параметр, нужный клиенту: было бы круто 44100 брать не из конфига, а читать из файла. Я могу предоставить эту инфу со стороны сервера, если надо.
3. Внутри нет никакого округления. Да, в консоль пишется число, округлённое до двух  цифр после запятой. Ну это же юзер-интерфейс, для читабельности.

**Comment by artyompal** [comment]
Допустимые значения:
window-size=256 - 65536, только степени двойки
minimum-amp=1e-5 -1.0
max-freq=1 - 22050 целые
min-metric=-10.0 - 0.0 вещественные числа
filter-overtones = true/false
filter-noise=true/false
overtone-epsilon = 0.0...1.0 вещественные
window-func = любая строка из списка

**Comment by doomsower** [comment]
Осталось использовать windowSize внутри прила

**Comment by doomsower** [comment]
Короче я хотел было применить этот самый windowSize и понял один момент. Использовать windowSize из настроек для воспроизведения нот нельзя, т.к. в нотах время записано в бэндах. Соответственно, если юзер зайдет и поковыряет настройки, то пересчет бэнд в секунды изменится, и ноты будут играть неправильно. Поэтому мне нужно сохранять windowSize, с которым был открыт файл. Это не проблема и сейчас я так сделаю.
Но мне кажется, файл JSON должен содержать в себе, помимо нот, информацию о том, как его проигрывать. Тут я вижу два варианта - либо пересчитать бэнды в секунды в бинарнике, либо добавить к JSON информацию о том, с какими настройками он был получен. Делать это надо в бинарнике, на сервере это делать по-моему не правильно, т.к. сервер становится зависим, чего хотелось бы избежать. Он и сейчас зависим, т.к. ему приходится фильтровать параметры, потому что бинарник падает если ему дать неподдерживаемый параметр впридачу к нормальным.

**Comment by doomsower** [comment]
Т.е. в более широком смысле слова версионность нужна не только моим .melody файлам, но и твоим .json файлам

**Comment by doomsower** [comment]
Короче коммит 80b06cfed14aa6462145fb487f97ef41736128cc закрывает этот баг в начальном виде.

**Comment by artyompal** [comment]
Тебе в клиенте все эти бенды не нужны же? Может, просто использовать в json-е секунды, и не надо будет никаких версий хранить?

sound2notes не должен бы падать. Где осуществляется фильтрация параметров? Я ожидал, что на клиенте, в диалоговом окне конфигурации. Я даже это проверял. Про какую лишнюю фильтрацию ты говоришь?

**Comment by artyompal** [comment]
Я добавил в sound2notes проверку параметров, падать не должно.

**Comment by doomsower** [comment]
Если sound2notes будет делать JSON с скеундами, то да, бэнды в клиенте почти не нужны. Почти, т.к. сейчас курсор обновляется с частотой 1 раз за бэнд и это удобно, потому что его позиции совпадают с началами/концами прямоугольников.

Попробуй запустить sound2notes --melodic --window-size=4096 --some-bad-arg=111 sound.mp3 sound.json У меня он в таких случаях завершается с ошибкой. Но эта ошибка является просто выводом в консоль, процсс завершается с тем же кодом. Сервер в таком случае просто не может это конвертнуть в json и шлет ошибку клиенту. Поэтому сервер из параметров запроса оставляет только те, которые принимает sound2notes.

**Comment by artyompal** [comment]
Ну не падает же. Имхо на неподдерживаемый аргумент он и должен выдавать ошибку, а как иначе узнать, что всё нормально прошло?)

**Comment by doomsower** [comment]
Ну он не выдает ошибку, он выводит хелп в консоль. Ладно, это все несущественно

**Comment by artyompal** [comment]
Ну можно выдавать разные return codes, типа когда всё ок, возвращать 0; для некритичной ошибки возвращать 1; когда пиздец и нельзя ничего сделать, возвращать 2. (Это стандартная практика в Unix)

**Comment by doomsower** [comment]
Че в итоге-то с бэндами делать?

**Comment by doomsower** [comment]
BandSize = windowSize/samplingFrequency сейчас сохраняется в файле проекта. Так что пока закрываю.
