### ISSUE TITLE
При нажатии Pause синтезированные ноты продолжают играть

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#26]
Каждая нота играет до конца сэмпла (и раздаётся характерный щелчок).

**Comment by doomsower** [comment]
Это сделано, но есть один момент. Если поставить на паузу посреди ноты, то потом, когда опять жмешь на play, эта нота не будет проигрываться. Думаю, сделать так, чтобы она продолжила играть с паузы, будет весьма сложно.
