### ISSUE TITLE
При добавлении ноты удаляется другая нота

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#33]
![screenshot from 2016-04-25 22-47-00](https://cloud.githubusercontent.com/assets/15948033/14800114/a8e483ba-0b37-11e6-86be-8d0712423733.png)
Ноты на 35.8 и 36.4 почему-то взаимоисключающие: когда добавляешь одну, удаляется другая. Причём, они помещаются на разные струны. Конфликта в этом случае быть не должно.

И даже если бы они были на одной струне, то можно же подвинуть, ведь есть же место на соседних струнах. Конфликт есть только если совсем невозможно подвинуть ни на какую струну.

И в случае конфликта надо не удалять старую ноту, а не добавлять новую.

**Comment by doomsower** [comment]
А не можешь обе ноты скинуть/заскринить? Или это довольно легко на других нотах воспроизводится?

**Comment by artyompal** [comment]
Происходит очень часто на любых файлах. Если не сможешь воспроизвести,
попробуй скачать этот файл в vk?

**Comment by artyompal** [comment]
Послал файл на gmail-почту.

**Comment by artyompal** [comment]
Также это происходит, даже если ноты не перекрываются по времени (просто для двух соседних нот).

**Comment by doomsower** [comment]
Исправил этот баг. Если ты сделал какие-то сейвы с ним, то в этих сейвах он продолжит появляться, так что больше не надо их использовать.
