### ISSUE TITLE
Посчитать правильную громкость для синтезированных звуков

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#35]
Сейчас получается, что синтезированный звук иногда в 100 раз громче оригинала. Это добавляет геморрой при частом переключении туда-обратно. Предлагается сделать следующее.

В каждом бине, мы можем посчитать суммарную громкость музыки на данный момент: если звучат ноты с амплитудами amp1, amp2, amp3, то это:
amp = sqrt(amp1 ** 2 + amp2 ** 2 + amp3 * *2)

Если нота длинная, то нужно посчитать громкости во всех бинах и взять среди них среднее квадратическое.

Это надо посчитать один раз при создании ноты. При редактировании ноты пересчитывать необязательно.

**Comment by doomsower** [comment]
Так, че-то я недопонял опять. Во-первых, rms для amp1, amp2, amp3 будет sqrt((amp1*amp1 + amp2*amp2 + amp3*amp3)/3). Ну я посчитал rms для каждого бина, а потом для каждой ноты еще опять взял rms по ее бинам. Это все я проделал для исходных нот и сохранил в каждую ноту рядом с ее родным amp. Значения понятное дело не сильно отличаются от настоящих amp нот.
Ну теперь допустим я ноту выбираю. Совсем давно я при выборе брал amp от исходной ноты. Сейчас я даю ей amp = 1. Что надо ей давать теперь? Этот rms amp? Так он не сильно от обычного amp отличается. Может надо какую-то нормализацию делать?

**Comment by artyompal** [comment]
Хм, это не rms, это именно сумма квадратов, ну как формула длины вектора. Идея в следующем:
допустим, мы имеем 10 звуков с громкостями 0.1. А выделяем только одну ноту с самой низкой частотой (например, у многих нот бывает много гармоник). Тогда громкость по этой формуле была 0.31, а стала 0.1, т.е. стало в 3 раза тише. Или в 10 раз тише, если сила звука это квадрат амплитуды.

Так вот, идея в том, чтобы в этом случае давать этот посчитанный amp, т.е. 0.31, и тогда на слух громкость будет такая же.

**Comment by doomsower** [comment]
Так, т.е. для бина считаем не среднее квадратичное, а длину вектора. Ну допустим вот у нас такая нота с amp = 0.1 длится 10 бинов, и в кадом бине мы, допустим, посчитали meanAmp=0.31. Дальше для ноты мы считаем по всем ее бинам и получаем примерно `sqrt(0.31*0.31 * 10) =~ 0.98` Или же как раз по бинам уже среднее квадратичное надо, `sqrt(0.31*0.31 * 10 /10) = 0.31`?

**Comment by artyompal** [comment]
По бинам уже надо считать среднее, конечно. Я поправил исходный пост.
