### ISSUE TITLE
Наименования нот типа A2, B3 сдвинуты на одну октаву

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#39]
Например, на ноту 293 Гц говорится, что она D3, а согласно википедии, это D4:
https://en.wikipedia.org/wiki/Scientific_pitch_notation#Table_of_note_frequencies

**Comment by artyompal** [comment]
Возможно, это я внёс путаницу, и формулу вычисления питча надо поправить (прибавить или вычесть 12).

**Comment by doomsower** [comment]
Я че-то не понимаю, где этот баг проявляется?

**Comment by artyompal** [comment]
Проявляется при наведении мыши на ноту, когда в правой области отображаются все параметры ноты. Короче сделай, чтобы это название показывалось с новым сервером, и тогда посмотрим на него.
