### ISSUE TITLE
Некоторые ноты не имеет ручек для ресайза

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#46]

**Comment by doomsower** [comment]
Сейчас у ноты есть ручки по 5 пикселей шириной, чтобы не целиться при ресайзе. Все что между ними - область для перетаскивания. Если ширина ноты меньше 10 пикселей - ручки не показываются, только область для перетаскивания. Я вижу несколько вариантов
1) Забить на ручки. Но для узких нот все равно как-то надо решать, что выбирать - ресайз или перетаскивание. При ресайзе строго по границе наверное будет жесткий пиксель-хантинг.
2) Попробовать сделать так, чтобы ручки (ручка) появлялись снаружи при наведении на ноту.

**Comment by artyompal** [comment]
Не баг.

**Comment by doomsower** [comment]
А нафиг закрывать?

**Comment by artyompal** [comment]
Стоит позумиться, как ручки появляются. Забей на это.
