### ISSUE TITLE
При размещении ноты считать расстояние только от предыдущей ноты

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#47]

**Comment by doomsower** [comment]
Не понял совсем, про что это?

**Comment by artyompal** [comment]
Про выбор струны по ближайшим нескольким нотам

**Comment by doomsower** [comment]
Понятнее не стало. В смысле выбор лада/струны при добавлении новой ноты? Так он (лад) и так по ближайшей ноте считается.

**Comment by artyompal** [comment]
По ближайшей предыдущей ноте? Или по вообще ближайшей? Только по одной ноте?

**Comment by doomsower** [comment]
По ближайшей предыдущей. Причем нота должна быть не дальше чем константа из конфига. Вот фрагмент кода
```
//Find closest note to the left of this one
//(iteration order is not guaranteed)
var {neighbour} = _.reduce(
  state,
  (result, value) => {
    var d = note.time - value.time;
    if (d >= 0 && d < result.delta)
      return {delta: d, neighbour: value};
    else
      return result;
  },
  {delta: Config.tabulatureProximityThreshold, neighbour: null}
);
```

**Comment by artyompal** [comment]
Тогда тут ничего не нужно делать, я это закрываю.
