### ISSUE TITLE
Вёрстка: сделать кнопки Open file / Save project / Export tab одинаковой ширины

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#48]

**Comment by doomsower** [comment]
Не совсем понял, чего ты хочешь. Сейчас справа от кнопки открыть кнопка с настройками. Надо кнопки для сохранения сделать шириной как открыть, а справа от них оставить пустое место, под настройками?

**Comment by artyompal** [comment]
Да) Как-то криво сейчас выглядит.

**Comment by doomsower** [comment]
Ну, по-моему так только хуже
