### ISSUE TITLE
Зум: сделать, чтобы колесо зумило к курсору, а не к началу выделения

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#50]

**Comment by doomsower** [comment]
Тоже не очень понял, что имеется в виду. Допустим ты навел курсор в район 300й секунды и зумишь. Так вот дальше на любом масштабе при кручении колеса под курсором будет оставаться 300я секунда. Сейчас поведение такое, и по-моему это и есть зум к курсору.

**Comment by artyompal** [comment]
Вроде сейчас происходит не так. Если допустим в видимом диапазоне у нас от 298 до 302 сек, а курсор на 300, то я бы ожидал от зума зумить к 300 (т.е. 300 — неподвижная точка). Но зумит к 298. Могу перепроверить вечером.

**Comment by doomsower** [comment]
Перепроверь плз

**Comment by artyompal** [comment]
А, оно зумит не к курсору проигрывателя, а к мышиному курсору.
