### ISSUE TITLE
Если кликнули на табулятуре, но не на ноте, показать контекстное меню

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#51]
В меню должен быть один пункт: " Create note", по нему диалог редактирования, аналогичный диалогу редактирования pitch, но ещё надо задать длину ноты в разумных пределах (например, 0.01 сек - 10 сек).

**Comment by doomsower** [comment]
Это диалог привязан к струне? Или струна внутри него выбирается? В каком виде делаем выбор питча и времени, с учетом ограничений, который накладываются струной и уже существующими нотаами?

**Comment by artyompal** [comment]
Не привязан к струне. Вводится только питч, струна определяется точно так же, как при добавлении ноты из верхней панели. Питч без ограничений. Длительность -- так же, как и при обычном добавлении: я так понимаю, оно ищет подходящую струну, куда можно втиснуть, а если невозможно, просто не добавляет.

**Comment by artyompal** [comment]
У тебя же есть вся эта функциональность! Просто представь, что кликнули на ноту, у которой есть введённый питч и введённая длина, и добавляй точно так же.

**Comment by doomsower** [comment]
Т.е. если добавили не на ту струну, то потом просто вручную перетаскиваем?
Также насчет втискивания. Делаем втупую, т.е. по координате X мыши будет выставляться начало (или середина?) ноты, если не влазит - облом. Покатызавем снэк-соообщение, но диалог не закрываем. Норм?

**Comment by artyompal** [comment]
Вообще игнорировать, на какую струну добавили. Добавлять куда захочется (то есть, как сейчас добавляются ноты: по минимуму расстояния между ладами с предыдущей нотой).
По Х мыши начало ноты, если не лезет, то облом, да. Так нормально.

**Comment by doomsower** [comment]
Короче добавил такой диалог. Есть вопрос. Я создаю эту ноту с amp=0.5, сойдет?

**Comment by artyompal** [comment]
Нет,  по громкости может сильно отличаться. Ты можешь сделать такой же подсчет громкости, как и при обычной вставке нот? Она же у тебя вроде там один раз подсчитывается и потом кешируется.

**Comment by doomsower** [comment]
Ну код уже написан, приспособить можно, кэширования сейчас нет, т.к. после того, как я посчитал meanAmp у ноты, у меня нет необходимости хранить meanAmp по бэндам. Но для такой фичи это наверное может стать осмысленным ( а может и нет, т.к. нам не нужен meanAmp по всем бендам, а только по тем, которые попадают в интервал ноты. А его и посчитать не так напряжно).
