### ISSUE TITLE
Очень неудобно прокручивать при сильном зуме: полоска для таскания слишком узкая

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#54]
Надо ввести для неё какой-то минимальный размер, когда в неё ещё удобно попасть мышью.

**Comment by artyompal** [comment]
Например, шириной с курсор мыши (который в виде руки с пятью пальцами, когда наводишь курсор на браш).

**Comment by doomsower** [comment]
Короче вот коммит, сделал минимальную ширину 12. 
Если зазумить меньше, то при перетаскивании/ресайзе будет наблюдаться сначал странное поведение, т.к. ширина и позиции краев браша отличаются от фактического выделения по времени.
Есть идеи как с этим бороться?

**Comment by artyompal** [comment]
Как у скролл-баров в винде (и где угодно). Мне кажется, они просто по ползунка берут позицию, а позиции краёв игнорируют вообще. Зачем сейчас используются позиции краёв?

**Comment by doomsower** [comment]
За позиции краев можно таскать и менять размер выделения же.

**Comment by doomsower** [comment]
Т.е. винде ползунки только для позиционирования, а у нас еще и для ресайза

**Comment by artyompal** [comment]
Хм, не знаю. Есть альтернатива: просто сделать, чтобы мышью можно было таскать экран влево-вправо, и таким образом, скроллить его. А браши не ограничивать.

Только мне кажется, что браш шириной в 1 пиксель всё равно какой-то неюзабельный. Как в других прогах? Где есть браши вообще?

**Comment by artyompal** [comment]
Либо, при минимальном зуме браш должен становиться "деревянным" и нерастягиваемым мышью (только колесом можно раззумиться). Если раззумиться, то он должен работать нормально. Так проще?

**Comment by doomsower** [comment]
Ну вообще я такой контрол встречал только в музыкальных и видео редакторах. В Adobe Premiere, например. Правда он сейчас не стоит у меня, надо ставить, чтобы посмотреть. Ширина у меня не 1 пикс, а 12.Делать браш деревянным при больших зумах нехорошо, т.к. это вызывает непонимание. С тасканием влево-вправо за экран есть проблема - у нас по клику уже курсор перемещается.
Ты в текущем виде попробовал? Может оно не так и плохо.

**Comment by artyompal** [comment]
Вообще, все нормально, закрываем.
