### ISSUE TITLE
Зум колесом мыши не всегда работает над табулятурой

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#62]
Над областью с нотами и частотами он работает всегда. Если потом продолжить крутить колесо над табулятурой, то тоже работает. Но потом над табулятурой он работать перестаёт. В общем, через раз. Желательно иметь какое-то одно поведение.

**Comment by artyompal** [comment]
И одиночный клик над табулятурой так же нестабильно работает. Тыкаю в случайных местах, сработал 7 раз из 10ти.

**Comment by doomsower** [comment]
Да, там у каждой струны есть область где она реагирует на мышь. Сейчас между струнами в этом плане есть дырки. Это можно видеть когда пытаешься перетащить ноту на соседнюю струну. Сначала она пропадает со своей струны, но на новой струне появляется не сразу, а надо еще немного протащить. Это я сделал когда ноты еще по-старому перетаскивались, с превью. Я думаю, надо сделать, чтобы области струн вплотную прилегали. Тогда и этот баг отпадет. Ну или можно сделать отдельную подложку для колеса, но перетаскивание оставить с дырками. Что думаешь?

**Comment by artyompal** [comment]
Вплотную сделай, так же проще всего?

**Comment by doomsower** [comment]
И так и так не сложно.
Просто такое вот поведение с дырками осталось от старой версии, где оно было нормальным. Наверное и его заодно убрать лучше?

**Comment by artyompal** [comment]
Убрать, да
