### ISSUE TITLE
Split into 2/3 всегда разбивает на 4 части

### ISSUE THREAD

**Issue by artyompal** [doomsower/melody#64]
И вообще все пункты контекстного меню: Delete сначала разбивает на 3, потом удаляет одну из них.

**Comment by artyompal** [comment]
Ни одну ноту нельзя удалить: у неё, как у Гидры, вырастают новые головы!

**Comment by doomsower** [comment]
Че-то у меня не получается воспроизвести сходу

**Comment by artyompal** [comment]
У тебя же есть файл Cream - Sunshine of your love? Вот я просто открыл и выделил ноты, питч 56 старт 18.344, 18.878 и они разбиваются на 3 уже по правому клику мышкой (до того, как в меню что-то выберешь).

**Comment by doomsower** [comment]
У меня не получается. Можешь ссылку на конкретный файл дать?

**Comment by artyompal** [comment]
Послал тебе в гмейл-почту. Но похоже, что у меня это происходит всегда, а у тебя никогда. Пробую на линукс/хромиум.

**Comment by artyompal** [comment]
Сделал полный ребилд всего, то же самое.

**Comment by doomsower** [comment]
Короче это злостный баг.
Вроде исправил, протестировал в последних хроме и фф на финде и на убунте
